### ISSUE TITLE
Version 0.9.1 is not available on Rubygems

### ISSUE THREAD

**Issue by jurriaan** [blendle/cucumber-blendle-steps#9]
I thought this was fixed recently, but Rubygems doesn't have 0.9.1.

See https://rubygems.org/gems/cucumber-blendle-steps

Can I somehow get access to push gems here?

cc @JeanMertz

**Comment by koenrh** [comment]
https://rubygems.org/gems/cucumber-blendle-steps/versions/0.9.1
